/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.acme.sg.Dto;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2019-12-16")
public class MachineInfoResult implements org.apache.thrift.TBase<MachineInfoResult, MachineInfoResult._Fields>, java.io.Serializable, Cloneable, Comparable<MachineInfoResult> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MachineInfoResult");

  private static final org.apache.thrift.protocol.TField MACHINE_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("machineInfo", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new MachineInfoResultStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new MachineInfoResultTupleSchemeFactory();

  public java.util.List<MachineInfo> machineInfo; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MACHINE_INFO((short)1, "machineInfo");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MACHINE_INFO
          return MACHINE_INFO;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MACHINE_INFO, new org.apache.thrift.meta_data.FieldMetaData("machineInfo", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT            , "MachineInfo"))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MachineInfoResult.class, metaDataMap);
  }

  public MachineInfoResult() {
  }

  public MachineInfoResult(
    java.util.List<MachineInfo> machineInfo)
  {
    this();
    this.machineInfo = machineInfo;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MachineInfoResult(MachineInfoResult other) {
    if (other.isSetMachineInfo()) {
      java.util.List<MachineInfo> __this__machineInfo = new java.util.ArrayList<MachineInfo>(other.machineInfo.size());
      for (MachineInfo other_element : other.machineInfo) {
        __this__machineInfo.add(new MachineInfo(other_element));
      }
      this.machineInfo = __this__machineInfo;
    }
  }

  public MachineInfoResult deepCopy() {
    return new MachineInfoResult(this);
  }

  @Override
  public void clear() {
    this.machineInfo = null;
  }

  public int getMachineInfoSize() {
    return (this.machineInfo == null) ? 0 : this.machineInfo.size();
  }

  public java.util.Iterator<MachineInfo> getMachineInfoIterator() {
    return (this.machineInfo == null) ? null : this.machineInfo.iterator();
  }

  public void addToMachineInfo(MachineInfo elem) {
    if (this.machineInfo == null) {
      this.machineInfo = new java.util.ArrayList<MachineInfo>();
    }
    this.machineInfo.add(elem);
  }

  public java.util.List<MachineInfo> getMachineInfo() {
    return this.machineInfo;
  }

  public MachineInfoResult setMachineInfo(java.util.List<MachineInfo> machineInfo) {
    this.machineInfo = machineInfo;
    return this;
  }

  public void unsetMachineInfo() {
    this.machineInfo = null;
  }

  /** Returns true if field machineInfo is set (has been assigned a value) and false otherwise */
  public boolean isSetMachineInfo() {
    return this.machineInfo != null;
  }

  public void setMachineInfoIsSet(boolean value) {
    if (!value) {
      this.machineInfo = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case MACHINE_INFO:
      if (value == null) {
        unsetMachineInfo();
      } else {
        setMachineInfo((java.util.List<MachineInfo>)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case MACHINE_INFO:
      return getMachineInfo();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case MACHINE_INFO:
      return isSetMachineInfo();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof MachineInfoResult)
      return this.equals((MachineInfoResult)that);
    return false;
  }

  public boolean equals(MachineInfoResult that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_machineInfo = true && this.isSetMachineInfo();
    boolean that_present_machineInfo = true && that.isSetMachineInfo();
    if (this_present_machineInfo || that_present_machineInfo) {
      if (!(this_present_machineInfo && that_present_machineInfo))
        return false;
      if (!this.machineInfo.equals(that.machineInfo))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetMachineInfo()) ? 131071 : 524287);
    if (isSetMachineInfo())
      hashCode = hashCode * 8191 + machineInfo.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(MachineInfoResult other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetMachineInfo()).compareTo(other.isSetMachineInfo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMachineInfo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.machineInfo, other.machineInfo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("MachineInfoResult(");
    boolean first = true;

    sb.append("machineInfo:");
    if (this.machineInfo == null) {
      sb.append("null");
    } else {
      sb.append(this.machineInfo);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MachineInfoResultStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public MachineInfoResultStandardScheme getScheme() {
      return new MachineInfoResultStandardScheme();
    }
  }

  private static class MachineInfoResultStandardScheme extends org.apache.thrift.scheme.StandardScheme<MachineInfoResult> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, MachineInfoResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MACHINE_INFO
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.machineInfo = new java.util.ArrayList<MachineInfo>(_list0.size);
                MachineInfo _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = new MachineInfo();
                  _elem1.read(iprot);
                  struct.machineInfo.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setMachineInfoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, MachineInfoResult struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.machineInfo != null) {
        oprot.writeFieldBegin(MACHINE_INFO_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.machineInfo.size()));
          for (MachineInfo _iter3 : struct.machineInfo)
          {
            _iter3.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MachineInfoResultTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public MachineInfoResultTupleScheme getScheme() {
      return new MachineInfoResultTupleScheme();
    }
  }

  private static class MachineInfoResultTupleScheme extends org.apache.thrift.scheme.TupleScheme<MachineInfoResult> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MachineInfoResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetMachineInfo()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetMachineInfo()) {
        {
          oprot.writeI32(struct.machineInfo.size());
          for (MachineInfo _iter4 : struct.machineInfo)
          {
            _iter4.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MachineInfoResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.machineInfo = new java.util.ArrayList<MachineInfo>(_list5.size);
          MachineInfo _elem6;
          for (int _i7 = 0; _i7 < _list5.size; ++_i7)
          {
            _elem6 = new MachineInfo();
            _elem6.read(iprot);
            struct.machineInfo.add(_elem6);
          }
        }
        struct.setMachineInfoIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

